apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: "{{APP_NAME}}"

commonLabels:
  app.kubernetes.io/name: "{{APP_NAME}}"
  app.kubernetes.io/managed-by: kustomize

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: "{{APP_NAME}}-config"
    literals:
      - APP_ENV=production
      - LOG_LEVEL=info
      - PORT=8080
